name: teleceriado
description: A new Flutter project.
publish_to: 'none'
version: 3.0.3+6

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  email_validator: ^2.1.17
  firebase_auth: ^4.6.3
  # firebase_core: ^2.13.0
  # firebase_database: ^10.2.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  google_sign_in: ^6.1.4
  http: ^1.1.0
  http_interceptor: ^2.0.0-beta.7
  image: ^4.0.17
  logger: ^1.3.0
  package_info_plus: ^4.0.2
  pixel_snap: ^0.1.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.10
  brasil_fields: ^1.9.1
  firebase_storage: ^11.2.5
  path: ^1.8.3
  image_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
