name: teleceriado
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  http_interceptor: ^1.0.2
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
