name: teleceriado
description: A new Flutter project.
publish_to: 'none'
version: 2.0.3

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_database: ^10.2.2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  google_sign_in: ^6.1.4
  http: ^0.13.5
  http_interceptor: ^1.0.2
  logger: ^1.3.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
